version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    command: uvicorn server.core.processor:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container:
